travis:
  secure:
    BINSTAR_TOKEN: t0834JVSvC97MKWf/8KKJX4IhTMocw28hlouTstZso9Df5tCyML+6NItNmJ0wHMCsHSHlSHdicAPQm0UtnFEicg5sJWqxHx5vNeOBIWKcnlarFEDTvmiXJo8834EfgofK+ANYxZVmvLYLoxYCVx+A4mlFnpp6YuKJC/BeGbIEX08iJONjQFYdS78IKwfIOfgDiE6/O6wXSsfercsNl/EhCfS7BBLr3jRSgpzPfRPIE56RZduL1GFeiYKoA5fC+zlwt/WXN70i+tF/pVLWbDX7xwZbXEZ7KFHWV4XrSABB80hBvGQbQ7DhrebOwQEolfI7vU1KRBDT45nYDZJbLV/8BSsJSfaiyEB8+1EkKvL/jdfNV1v4nZm27bqfkyEZ9Zbqxi3vMEYKqO3FCnE9zQ3EuyiyCBz44YB59wphxP0P5vCPKwA6Qd5GO4Jbbvgs715NSsNtWn6EP3zEeRfVgMA7Tn0vwG22E2Jmp7RmcNBoOmJxCVOxT1bOgQh4i8Hsupg4EmP7yyzTH0uRJilEojNhWvxrPjThdhh+Joq2aWysNh2hoYIEKyq5uzj2qAcKZ5VgVoaQ4+gyHDTZ/UfSw67weJGTu28q2IFxZU2zEl2/ZZF9aGiYYn3DqrApFct9YFos4lye3d35YIq0eq/h3ah6Vhw4W7Diw0i4JU+tCLoLGc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
